# Generated by Django 4.2.30 on 2026-04-28 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbutzot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='janij',
            name='edad',
        ),
        migrations.AddField(
            model_name='janij',
            name='info_medica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='janij',
            name='nombre_mama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='janij',
            name='nombre_papa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='janij',
            name='tel_mama',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='janij',
            name='tel_papa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='janij',
            name='kbutza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbutzot.kbutza'),
        ),
    ]
