# Generated by Django 4.2.30 on 2026-04-29 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbutzot', '0002_remove_janij_edad_janij_info_medica_and_more'),
        ('usuarios', '0001_initial'),
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShevetBankCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=30, unique=True)),
                ('saldo', models.IntegerField(default=0)),
                ('janij', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kbutzot.janij')),
            ],
        ),
        migrations.CreateModel(
            name='ShevetBankEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('encargado', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'madrij'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariocamp')),
            ],
        ),
        migrations.CreateModel(
            name='ShevetBankMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('nota', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.shevetbankcuenta')),
                ('estacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.shevetbankestacion')),
                ('madrij', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariocamp')),
            ],
        ),
    ]
