# Generated by Django 4.2.30 on 2026-05-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_shevetbankcuenta_shevetbankestacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('abierta', models.BooleanField(default=False)),
            ],
        ),
    ]
