# Generated by Django 4.2.30 on 2026-05-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_actividadestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='shevetbankestacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
