# Generated by Django 4.2.30 on 2026-05-17 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbutzot', '0002_remove_janij_edad_janij_info_medica_and_more'),
        ('usuarios', '0001_initial'),
        ('actividades', '0004_shevetbankestacion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShevetBankSubasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premio', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=False)),
                ('precio_actual', models.IntegerField(default=0)),
                ('termina_en', models.DateTimeField(blank=True, null=True)),
                ('kbutza_ganando', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbutzot.kbutza')),
            ],
        ),
        migrations.CreateModel(
            name='ShevetBankPuja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('kbutza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbutzot.kbutza')),
                ('madrij', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariocamp')),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.shevetbanksubasta')),
            ],
        ),
    ]
