# Generated by Django 4.2.30 on 2026-05-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_shevetbanksubasta_shevetbankpuja'),
    ]

    operations = [
        migrations.AddField(
            model_name='shevetbanksubasta',
            name='cobrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shevetbanksubasta',
            name='duracion_minutos',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='shevetbanksubasta',
            name='iniciada',
            field=models.BooleanField(default=False),
        ),
    ]
