# Generated by Django 4.2.30 on 2026-05-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_shevetbanksubasta_cobrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shevetbanksubasta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='subastas/'),
        ),
    ]
