# Generated by Django 4.2.30 on 2026-05-27 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('kbutzot', '0002_remove_janij_edad_janij_info_medica_and_more'),
        ('actividades', '0007_shevetbanksubasta_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShivteGotTalentRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariocamp')),
            ],
        ),
        migrations.CreateModel(
            name='ShivteGotTalentConcursante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talento', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=False)),
                ('terminado', models.BooleanField(default=False)),
                ('janij', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbutzot.janij')),
            ],
        ),
        migrations.CreateModel(
            name='ShivteGotTalentCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalidad', models.IntegerField()),
                ('ejecucion', models.IntegerField()),
                ('general', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('concursante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.shivtegottalentconcursante')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariocamp')),
            ],
            options={
                'unique_together': {('concursante', 'juez')},
            },
        ),
    ]
