# Generated by Django 4.2.30 on 2026-05-29 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbutzot', '0002_remove_janij_edad_janij_info_medica_and_more'),
        ('usuarios', '0001_initial'),
        ('actividades', '0008_shivtegottalentrol_shivtegottalentconcursante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShivteTVPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('kbutza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbutzot.kbutza')),
            ],
        ),
        migrations.CreateModel(
            name='ShivteTVVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='shivte_tv/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actividades.shivtetvpedido')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariocamp')),
            ],
        ),
    ]
