# Generated by Django 4.2.30 on 2026-06-07 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('actividades', '0009_shivtetvpedido_shivtetvvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShevetBankGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_oculto', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShevetBankRondaEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('bote', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariocamp')),
            ],
        ),
        migrations.AddField(
            model_name='shevetbankestacion',
            name='es_banco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shevetbankestacion',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ShevetBankRondaParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobrado', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.shevetbankcuenta')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.shevetbankrondaestacion')),
            ],
        ),
        migrations.AddField(
            model_name='shevetbankrondaestacion',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.shevetbankestacion'),
        ),
        migrations.AddField(
            model_name='shevetbankrondaestacion',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondas_ganadas', to='actividades.shevetbankcuenta'),
        ),
        migrations.CreateModel(
            name='ShevetBankGrupoMadrij',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.shevetbankgrupo')),
                ('madrij', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariocamp')),
            ],
        ),
        migrations.CreateModel(
            name='ShevetBankGrupoJanij',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.shevetbankcuenta')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.shevetbankgrupo')),
            ],
        ),
    ]
