# Generated by Django 4.2.30 on 2026-06-07 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_shevetbankgrupo_shevetbankrondaestacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shevetbankpuja',
            name='kbutza',
        ),
        migrations.RemoveField(
            model_name='shevetbanksubasta',
            name='kbutza_ganando',
        ),
        migrations.AddField(
            model_name='shevetbankpuja',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.shevetbankgrupo'),
        ),
        migrations.AddField(
            model_name='shevetbanksubasta',
            name='grupo_ganando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.shevetbankgrupo'),
        ),
    ]
