# Generated by Django 4.2.30 on 2026-06-07 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('actividades', '0011_remove_shevetbankpuja_kbutza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShevetBankParticipanteRonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShevetBankPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('abierto', models.BooleanField(default=True)),
                ('pagado', models.BooleanField(default=False)),
                ('cobrado_doble', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.shevetbankestacion')),
            ],
        ),
        migrations.CreateModel(
            name='ShevetBankRonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('bote', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariocamp')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.shevetbankestacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='shevetbankrondaestacion',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='shevetbankrondaestacion',
            name='estacion',
        ),
        migrations.RemoveField(
            model_name='shevetbankrondaestacion',
            name='ganador',
        ),
        migrations.RemoveField(
            model_name='shevetbankrondaparticipante',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='shevetbankrondaparticipante',
            name='ronda',
        ),
        migrations.RenameField(
            model_name='shevetbanksubasta',
            old_name='cobrada',
            new_name='cerrada',
        ),
        migrations.RemoveField(
            model_name='shevetbankgrupo',
            name='codigo_oculto',
        ),
        migrations.RemoveField(
            model_name='shevetbanksubasta',
            name='duracion_minutos',
        ),
        migrations.RemoveField(
            model_name='shevetbanksubasta',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='shevetbanksubasta',
            name='termina_en',
        ),
        migrations.AddField(
            model_name='shevetbankcuenta',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.shevetbankgrupo'),
        ),
        migrations.AddField(
            model_name='shevetbankgrupo',
            name='revelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shevetbankmovimiento',
            name='estacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.shevetbankestacion'),
        ),
        migrations.AlterField(
            model_name='shevetbankmovimiento',
            name='madrij',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariocamp'),
        ),
        migrations.AlterField(
            model_name='shevetbankmovimiento',
            name='nota',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shevetbankpuja',
            name='madrij',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariocamp'),
        ),
        migrations.DeleteModel(
            name='ShevetBankGrupoJanij',
        ),
        migrations.DeleteModel(
            name='ShevetBankRondaEstacion',
        ),
        migrations.DeleteModel(
            name='ShevetBankRondaParticipante',
        ),
        migrations.AddField(
            model_name='shevetbankronda',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondas_ganadas', to='actividades.shevetbankcuenta'),
        ),
        migrations.AddField(
            model_name='shevetbankprestamo',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.shevetbankcuenta'),
        ),
        migrations.AddField(
            model_name='shevetbankprestamo',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariocamp'),
        ),
        migrations.AddField(
            model_name='shevetbankparticipanteronda',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.shevetbankcuenta'),
        ),
        migrations.AddField(
            model_name='shevetbankparticipanteronda',
            name='ronda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.shevetbankronda'),
        ),
    ]
