# Generated by Django 4.2.30 on 2026-06-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_shevetbankparticipanteronda_shevetbankprestamo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShevetBankConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupos_revelados', models.BooleanField(default=False)),
                ('actividad_activa', models.BooleanField(default=True)),
            ],
        ),
    ]
