# Generated by Django 4.2.30 on 2026-04-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_camp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotocamp',
            name='imagen',
        ),
        migrations.AddField(
            model_name='fotocamp',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='media_camp/'),
        ),
        migrations.AddField(
            model_name='fotocamp',
            name='tipo',
            field=models.CharField(default='foto', max_length=20),
        ),
    ]
