from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from torneo.views import (
    inicio,
    panel_admin,
    madrijim,
    detalle_madrij,
    editar_madrij,
    eliminar_madrij,
    kbutzot_admin,
    detalle_kbutza,
    editar_kbutza,
    agregar_janij,
    actividades,
    horarios,
    fotos,
    inscripciones,
    transporte,
    eliminar_kbutza,
    quitar_madrij_kbutza,
    editar_janij,
    eliminar_janij,
    horarios_admin,
    editar_horario,
    eliminar_horario, 
    transporte_admin,
    editar_camion,
    eliminar_camion,
    detalle_camion,
    quitar_madrij_camion,
    quitar_kbutza_camion, 
    quitar_janij_camion,
    transporte_publico,  
    login_view,
    logout_view,
    menu_madrij,  
    transporte_madrij,
    fotos_publicas,
    subir_foto,
    eliminar_foto,
    kbutzot_publicas,
    janijim_publicos,
    detalle_janij_publico,
    agregar_janij_general,
    editar_janij_general,
    eliminar_janij_general,
    crear_admin_temporal,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('panel-admin/', panel_admin, name='panel_admin'),

    path('panel-admin/madrijim/', madrijim, name='madrijim'),
    path('panel-admin/madrijim/<int:madrij_id>/', detalle_madrij, name='detalle_madrij'),
    path('panel-admin/madrijim/<int:madrij_id>/editar/', editar_madrij, name='editar_madrij'),
    path('panel-admin/madrijim/<int:madrij_id>/eliminar/', eliminar_madrij, name='eliminar_madrij'),

    path('panel-admin/kbutzot/', kbutzot_admin, name='kbutzot_admin'),
    path('panel-admin/kbutzot/<int:kbutza_id>/', detalle_kbutza, name='detalle_kbutza'),
    path('panel-admin/kbutzot/<int:kbutza_id>/editar/', editar_kbutza, name='editar_kbutza'),
    path('panel-admin/kbutzot/<int:kbutza_id>/eliminar/', eliminar_kbutza, name='eliminar_kbutza'),
    path('panel-admin/kbutzot/<int:kbutza_id>/agregar-janij/', agregar_janij, name='agregar_janij'),

    path('actividades/', actividades, name='actividades'),
    path('horarios/', horarios, name='horarios'),
    path('inscripciones/', inscripciones, name='inscripciones'),
    path('transporte/', transporte, name='transporte'),
    path('panel-admin/kbutzot/<int:kbutza_id>/quitar-madrij/<int:asignacion_id>/', quitar_madrij_kbutza, name='quitar_madrij_kbutza'),
    path('panel-admin/janijim/<int:janij_id>/editar/', editar_janij, name='editar_janij'),
    path('panel-admin/janijim/<int:janij_id>/eliminar/', eliminar_janij, name='eliminar_janij'),
    path('panel-admin/horarios/', horarios_admin, name='horarios_admin'),
    path('panel-admin/horarios/<int:horario_id>/editar/', editar_horario, name='editar_horario'),
    path('panel-admin/horarios/<int:horario_id>/eliminar/', eliminar_horario, name='eliminar_horario'),
    path('panel-admin/transporte/', transporte_admin, name='transporte_admin'),
    path('panel-admin/transporte/<int:camion_id>/editar/', editar_camion, name='editar_camion'),
    path('panel-admin/transporte/<int:camion_id>/eliminar/', eliminar_camion, name='eliminar_camion'),
    path('panel-admin/transporte/<int:camion_id>/', detalle_camion, name='detalle_camion'),
    path('panel-admin/transporte/<int:camion_id>/quitar-madrij/<int:asignacion_id>/', quitar_madrij_camion, name='quitar_madrij_camion'),
    path('panel-admin/transporte/<int:camion_id>/quitar-kbutza/<int:asignacion_id>/', quitar_kbutza_camion, name='quitar_kbutza_camion'),
    path('panel-admin/transporte/<int:camion_id>/quitar-janij/<int:asignacion_id>/', quitar_janij_camion, name='quitar_janij_camion'),
    path('transporte-publico/', transporte_publico, name='transporte_publico'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('menu-madrij/', menu_madrij, name='menu_madrij'),
    path('transporte-madrij/', transporte_madrij, name='transporte_madrij'),
    path('fotos/', fotos_publicas, name='fotos_publicas'),
    path('fotos/subir/', subir_foto, name='subir_foto'),
    path('fotos/<int:foto_id>/eliminar/', eliminar_foto, name='eliminar_foto'),
    path('kbutzot/', kbutzot_publicas, name='kbutzot_publicas'),
    path('janijim/', janijim_publicos, name='janijim_publicos'),
    path('janijim/<int:janij_id>/', detalle_janij_publico, name='detalle_janij_publico'),
    path('janijim/agregar/', agregar_janij_general, name='agregar_janij_general'),
    path('janijim/<int:janij_id>/editar/', editar_janij_general, name='editar_janij_general'),
    path('janijim/<int:janij_id>/eliminar/', eliminar_janij_general, name='eliminar_janij_general'),
    path('crear-admin-temporal/', crear_admin_temporal, name='crear_admin_temporal'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)