from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from torneo.views import (
    inicio,
    panel_admin,
    madrijim,
    detalle_madrij,
    editar_madrij,
    eliminar_madrij,
    kbutzot_admin,
    detalle_kbutza,
    editar_kbutza,
    agregar_janij,
    actividades,
    horarios,
    fotos,
    inscripciones,
    transporte,
    eliminar_kbutza,
    quitar_madrij_kbutza,
    editar_janij,
    eliminar_janij,
    horarios_admin,
    editar_horario,
    eliminar_horario, 
    transporte_admin,
    editar_camion,
    eliminar_camion,
    detalle_camion,
    quitar_madrij_camion,
    quitar_kbutza_camion, 
    quitar_janij_camion,
    transporte_publico,  
    login_view,
    logout_view,
    menu_madrij,  
    transporte_madrij,
    fotos_publicas,
    subir_foto,
    eliminar_foto,
    kbutzot_publicas,
    janijim_publicos,
    detalle_janij_publico,
    agregar_janij_general,
    editar_janij_general,
    eliminar_janij_general,
    crear_admin_temporal,
    picture_day_admin,
    picture_day_madrij,
    subir_picture_day,
    picture_day_publico,
    shevet_bank_admin,
    shevet_bank_madrij,
    shevet_bank_ranking,
    eliminar_picture_day_foto,
    descargar_picture_day_zip,
    picture_day_entrada,
    eliminar_picture_day_pedido,
    eliminar_shevet_bank_estacion,
    shevet_bank_subasta_admin,  
    shevet_bank_subasta_madrij,
    shevet_bank_subasta_pantalla,
    cerrar_shevet_bank_subasta,
    iniciar_shevet_bank_subasta,
    got_talent_admin,
    got_talent_inscripciones,
    got_talent_iniciar_concursante,
    got_talent_terminar_concursante,
    got_talent_pantalla,
    got_talent_juez,
    got_talent_resultados_admin,
    eliminar_got_talent_concursante,
    editar_got_talent_concursante,
    shivte_tv_admin,
    shivte_tv_madrij,
    subir_shivte_tv,
    shivte_tv_publico
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('panel-admin/', panel_admin, name='panel_admin'),

    path('panel-admin/madrijim/', madrijim, name='madrijim'),
    path('panel-admin/madrijim/<int:madrij_id>/', detalle_madrij, name='detalle_madrij'),
    path('panel-admin/madrijim/<int:madrij_id>/editar/', editar_madrij, name='editar_madrij'),
    path('panel-admin/madrijim/<int:madrij_id>/eliminar/', eliminar_madrij, name='eliminar_madrij'),

    path('panel-admin/kbutzot/', kbutzot_admin, name='kbutzot_admin'),
    path('panel-admin/kbutzot/<int:kbutza_id>/', detalle_kbutza, name='detalle_kbutza'),
    path('panel-admin/kbutzot/<int:kbutza_id>/editar/', editar_kbutza, name='editar_kbutza'),
    path('panel-admin/kbutzot/<int:kbutza_id>/eliminar/', eliminar_kbutza, name='eliminar_kbutza'),
    path('panel-admin/kbutzot/<int:kbutza_id>/agregar-janij/', agregar_janij, name='agregar_janij'),

    path('actividades/', actividades, name='actividades'),
    path('horarios/', horarios, name='horarios'),
    path('inscripciones/', inscripciones, name='inscripciones'),
    path('transporte/', transporte, name='transporte'),
    path('panel-admin/kbutzot/<int:kbutza_id>/quitar-madrij/<int:asignacion_id>/', quitar_madrij_kbutza, name='quitar_madrij_kbutza'),
    path('panel-admin/janijim/<int:janij_id>/editar/', editar_janij, name='editar_janij'),
    path('panel-admin/janijim/<int:janij_id>/eliminar/', eliminar_janij, name='eliminar_janij'),
    path('panel-admin/horarios/', horarios_admin, name='horarios_admin'),
    path('panel-admin/horarios/<int:horario_id>/editar/', editar_horario, name='editar_horario'),
    path('panel-admin/horarios/<int:horario_id>/eliminar/', eliminar_horario, name='eliminar_horario'),
    path('panel-admin/transporte/', transporte_admin, name='transporte_admin'),
    path('panel-admin/transporte/<int:camion_id>/editar/', editar_camion, name='editar_camion'),
    path('panel-admin/transporte/<int:camion_id>/eliminar/', eliminar_camion, name='eliminar_camion'),
    path('panel-admin/transporte/<int:camion_id>/', detalle_camion, name='detalle_camion'),
    path('panel-admin/transporte/<int:camion_id>/quitar-madrij/<int:asignacion_id>/', quitar_madrij_camion, name='quitar_madrij_camion'),
    path('panel-admin/transporte/<int:camion_id>/quitar-kbutza/<int:asignacion_id>/', quitar_kbutza_camion, name='quitar_kbutza_camion'),
    path('panel-admin/transporte/<int:camion_id>/quitar-janij/<int:asignacion_id>/', quitar_janij_camion, name='quitar_janij_camion'),
    path('transporte-publico/', transporte_publico, name='transporte_publico'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('menu-madrij/', menu_madrij, name='menu_madrij'),
    path('transporte-madrij/', transporte_madrij, name='transporte_madrij'),
    path('fotos/', fotos_publicas, name='fotos_publicas'),
    path('fotos/subir/', subir_foto, name='subir_foto'),
    path('fotos/<int:foto_id>/eliminar/', eliminar_foto, name='eliminar_foto'),
    path('kbutzot/', kbutzot_publicas, name='kbutzot_publicas'),
    path('janijim/', janijim_publicos, name='janijim_publicos'),
    path('janijim/<int:janij_id>/', detalle_janij_publico, name='detalle_janij_publico'),
    path('janijim/agregar/', agregar_janij_general, name='agregar_janij_general'),
    path('janijim/<int:janij_id>/editar/', editar_janij_general, name='editar_janij_general'),
    path('janijim/<int:janij_id>/eliminar/', eliminar_janij_general, name='eliminar_janij_general'),
    path('crear-admin-temporal/', crear_admin_temporal, name='crear_admin_temporal'),
    path('panel-admin/picture-day/', picture_day_admin, name='picture_day_admin'),
    path('picture-day/', picture_day_madrij, name='picture_day_madrij'),
    path('picture-day/subir/<int:pedido_id>/', subir_picture_day, name='subir_picture_day'),
    path('picture-day-publico/', picture_day_publico, name='picture_day_publico'), 
    path('actividades/', actividades, name='actividades'), 
    path('panel-admin/shevet-bank/', shevet_bank_admin, name='shevet_bank_admin'),
    path('shevet-bank/', shevet_bank_madrij, name='shevet_bank_madrij'),
    path('shevet-bank-ranking/', shevet_bank_ranking, name='shevet_bank_ranking'),
    path('panel-admin/picture-day/foto/<int:foto_id>/eliminar/', eliminar_picture_day_foto, name='eliminar_picture_day_foto'),
    path('panel-admin/picture-day/descargar/', descargar_picture_day_zip, name='descargar_picture_day_zip'),
    path('actividades/picture-day/', picture_day_entrada, name='picture_day_entrada'),
    path('panel-admin/picture-day/pedido/<int:pedido_id>/eliminar/', eliminar_picture_day_pedido, name='eliminar_picture_day_pedido'),
    path('panel-admin/shevet-bank/estacion/<int:estacion_id>/eliminar/', eliminar_shevet_bank_estacion, name='eliminar_shevet_bank_estacion'),
    path('panel-admin/shevet-bank/subasta/', shevet_bank_subasta_admin, name='shevet_bank_subasta_admin'),
    path('shevet-bank/subasta/', shevet_bank_subasta_madrij, name='shevet_bank_subasta_madrij'),
    path('shevet-bank/subasta/pantalla/', shevet_bank_subasta_pantalla, name='shevet_bank_subasta_pantalla'),
    path('panel-admin/shevet-bank/subasta/<int:subasta_id>/cerrar/', cerrar_shevet_bank_subasta, name='cerrar_shevet_bank_subasta'),
    path('panel-admin/shevet-bank/subasta/<int:subasta_id>/iniciar/', iniciar_shevet_bank_subasta, name='iniciar_shevet_bank_subasta'),
    path('panel-admin/got-talent/', got_talent_admin, name='got_talent_admin'),
    path('got-talent/inscripciones/', got_talent_inscripciones, name='got_talent_inscripciones'),
    path('panel-admin/got-talent/concursante/<int:concursante_id>/iniciar/', got_talent_iniciar_concursante, name='got_talent_iniciar_concursante'),
    path('panel-admin/got-talent/concursante/<int:concursante_id>/terminar/', got_talent_terminar_concursante, name='got_talent_terminar_concursante'),
    path('got-talent/pantalla/', got_talent_pantalla, name='got_talent_pantalla'),
    path('got-talent/juez/', got_talent_juez, name='got_talent_juez'),
    path('panel-admin/got-talent/resultados/', got_talent_resultados_admin, name='got_talent_resultados_admin'),
    path('panel-admin/got-talent/concursante/<int:concursante_id>/eliminar/', eliminar_got_talent_concursante, name='eliminar_got_talent_concursante'),
    path('panel-admin/got-talent/concursante/<int:concursante_id>/editar/',editar_got_talent_concursante,name='editar_got_talent_concursante'),
    path('panel-admin/shivte-tv/', shivte_tv_admin, name='shivte_tv_admin'),
    path('shivte-tv/', shivte_tv_madrij, name='shivte_tv_madrij'),
    path('shivte-tv/subir/<int:pedido_id>/', subir_shivte_tv, name='subir_shivte_tv'),
    path('shivte-tv-publico/', shivte_tv_publico, name='shivte_tv_publico'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)