# Generated by Django 4.2.30 on 2026-04-23 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('kbutzot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ida', 'Ida'), ('regreso', 'Regreso')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('saliendo', 'Saliendo'), ('en_camino', 'En camino'), ('llegando', 'Llegando'), ('llego', 'Llegó')], default='pendiente', max_length=20)),
                ('hora_salida', models.CharField(blank=True, max_length=20, null=True)),
                ('hora_estimada', models.CharField(blank=True, max_length=20, null=True)),
                ('link_ruta', models.TextField(blank=True, null=True)),
                ('encargado', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'madrij'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camiones_encargado', to='usuarios.usuariocamp')),
            ],
        ),
        migrations.CreateModel(
            name='CamionMadrij',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.camion')),
                ('madrij', models.ForeignKey(limit_choices_to={'tipo': 'madrij'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariocamp')),
            ],
        ),
        migrations.CreateModel(
            name='CamionJanij',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.camion')),
                ('janij', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbutzot.janij')),
            ],
        ),
    ]
