# Generated by Django 4.2.30 on 2026-04-23 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbutzot', '0001_initial'),
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.camion')),
                ('janij', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbutzot.janij')),
            ],
        ),
    ]
