# Generated by Django 4.2.30 on 2026-04-23 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('transporte', '0002_asistenciacamion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaMadrijCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.camion')),
                ('madrij', models.ForeignKey(limit_choices_to={'tipo': 'madrij'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariocamp')),
            ],
        ),
    ]
