# Generated by Django 4.2.30 on 2026-04-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=100)),
                ('hora', models.CharField(max_length=20)),
                ('actividad', models.CharField(max_length=200)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
